### ISSUE TITLE
#findadoula

### ISSUE THREAD

**Issue by DevGosB** [chihacknight/breakout-groups#146] opened 2018-03-07 02:36 UTC
### About the group
A high level overview of your breakout group. What problem are you trying to solve? Make this simple and jargon-free. Links are good too!

### Group leaders
Names and contact info for the people running this group.

### Who we're looking for
Describe the kinds of people who would be good for your group. Include the skills, domain knowledge and interests that will help make your project succeed.

### Tools
Describe the tools that you are using.

### Relevant Links
Any relevant links, e.g. a github repo, a demo site

### Where we meet
Where in the Braintree office do you meet? Flipping Tables? The cafeteria?

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment] 2018-03-27 22:19
looks to be a duplicate of https://github.com/chihacknight/breakout-groups/issues/148

**Closed by derekeder** 2018-03-27 22:19 UTC
